---
apiVersion: v1
kind: Namespace
metadata:
  name: qcguy


---
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: qcguy-configmap
#  namespace: qcguy
#data:
  # Configuration values can be set as key-value properties
  #database: mongodb
  #database_uri: mongodb://localhost:27017
  # Or set as complete file contents (even JSON!)
#  fromfile: /home/vik/IdeaProjects/qcguy-cms/config/
---
apiVersion: v1
kind: Service
metadata:
  name: qcguy
  namespace: qcguy
  labels:
    app: qcguy
    io.kompose.service: qcguy
spec:
  type: NodePort
  #loadBalancerIP: 192.168.49.234
  selector:
    io.kompose.service: qcguy
    app: qcguy
  ports:
    - port: 2368
      protocol: TCP
      name: "2368"
      nodePort: 30368
      targetPort: 2368
  #externalTrafficPolicy: Local
status:
  #loadBalancer:
  #  ingress:
  #    - ip: 192.168.49.234
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qcguy-pv-volume
  namespace: qcguy
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
#  storageClassName: do-block-storage
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: qcguy-content
#  labels:
#    app: qcguy-content
#spec:
#  storageClassName: ""
#  capacity:
#    storage: 250Mi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: qcguy
#    name: qcguy-content
#  nfs:
#    path: /tmp
#    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: qcguy-content-claim
  namespace: qcguy
  labels:
    app: qcguy-content-claim
    io.kompose.service: qcguy-content-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: manual
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: qcguy
    io.kompose.service: qcguy
  name: qcguy
  namespace: qcguy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qcguy
      io.kompose.service: qcguy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: qcguy
        app: qcguy
    spec:
      volumes:
        - name: qcguy-content-storage
          persistentVolumeClaim:
            claimName: qcguy-content-claim
        - name: qcguy-configmap-volume
          configMap:
            name: qcguy-configmap
            #items:
            # - key: config.production.json
            #    path: "./var/lib/ghost/config.production.json"
      containers:
        - env:
            - name: url
              value: https://www.qcguy.com
          image: ghost:latest
          #imagePullPolicy: Always
          name: qcguy
          ports:
            - containerPort: 2368
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: qcguy-content-storage
            - name: qcguy-configmap-volume
              mountPath: /var/lib/ghost/config.production.json
              subPath: config.production.json
      #restartPolicy: Never
status: {}